module: default
runtime: python27
vm: true
api_version: 1
threadsafe: yes

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

handlers:

- url: '/admin.*'
  script: main.app
  login : admin
  secure : always

- url: .*
  script: main.app
  secure : always
